{% set version = "4.0" %}

package:
  name: astropy-helpers
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/astropy-helpers/astropy-helpers-{{ version }}.tar.gz
  sha256: 4177101ca064f2fa40e513bcfa82571b61c18fb2016187c4912cd8bf5de536a8
  patches:
    - version.patch

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - astropy_helpers

about:
  home: https://github.com/astropy/astropy-helpers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: "Utilities for building and installing packages in the Astropy ecosystem"

extra:
  recipe-maintainers:
    - ocefpaf
