travis:
  secure:
    BINSTAR_TOKEN: PnVksGSHbR52NIDlIOz4HTP28H6XIJg2pVFmPsKfzti93ZVm+FMNyMSZIWkkop/oaOiEJnYU5rPUSSoo9Z7s6ajSPOxM567I0UwgTL9fpkWbvSBKUeHunc/GOP5s8SAGHpzjJkX6n82TcKsq+CTUeOOyXNS/v2WVh+zY24Mu9N5DyE3ogfNS3CU+tiuf/pbjGMSJmB2sbUdgJOq12vVgnzlcvRLWGuSY14v1JdJDJ+go+SBxyJj1jYlYXYQeH38XdAtdHglSwkdyFCXgEeZOn3XNe6/Ijzi3iCeAJQswDZVlwDXkZw3thDA0JA3P118WCXlXV4lZSvfZeHs4F8r4dJBTrsqWXvVosv0dK8zzWUdnV8TgWpABBeggFrR8F583lKfhk4p+WVsQeVux/WTTy0j6EP9OmPGkHLVJPFMGJF5iXQ59pDJmbk3zVkKLtWKeBsc9nmofLbHk/ArD3wvxY0O2w1aL1XqbsrZO2XzPQowsa5BGQICTBW/KeAY43DSzALitzqvjO2NVHmgWIhPvM9cgz+pPSY7Mbrgd/JDOceh2u3besuF6tJBPOW/YNH50T/MIKwUvduFTtF9ijg2dBVh8YnD+BkjYnLyqnImiDgvrOB+xh9uQunEcvTd9R6mt5KwnBoyh9MT2ireyVLhzCaKPDDe04eLqcYjfJYZzFHY=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
